# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 695)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(110, 40, 861, 591))
        self.frame.setMinimumSize(QtCore.QSize(861, 591))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setToolTipDuration(0)
        self.frame_6.setStyleSheet("Qframe{\n"
"  border:none;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label = QtWidgets.QLabel(self.frame_6)
        self.label.setGeometry(QtCore.QRect(80, 10, 101, 41))
        self.label.setStyleSheet("font: 15pt \"Algerian\";\n"
"color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 10, 41, 41))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/OIP-C (2).jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setStyleSheet("Qframe{\n"
"  border:none;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/下载.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/1jpg.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.horizontalLayout_2.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("background-color: rgb(0, 85, 255);\n"
";\n"
"border-bottom-left-radius:30px\n"
"\n"
"    ")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_Seach = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Seach.setStyleSheet("font: 18pt \"Algerian\";\n"
"color: rgb(255, 255, 255);\n"
"pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"")
        self.pushButton_Seach.setObjectName("pushButton_Seach")
        self.verticalLayout_2.addWidget(self.pushButton_Seach)
        self.pushButton_Edit = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Edit.setStyleSheet("font: 18pt \"Algerian\";\n"
"color: rgb(255, 255, 255);\n"
"pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"\n"
"")
        self.pushButton_Edit.setObjectName("pushButton_Edit")
        self.verticalLayout_2.addWidget(self.pushButton_Edit)
        self.pushButton_My = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_My.setStyleSheet("font: 18pt \"Algerian\";\n"
"color: rgb(255, 255, 255);\n"
"pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}\n"
"\n"
"")
        self.pushButton_My.setObjectName("pushButton_My")
        self.verticalLayout_2.addWidget(self.pushButton_My)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_8)
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_my = QtWidgets.QWidget()
        self.page_my.setObjectName("page_my")
        self.label_3 = QtWidgets.QLabel(self.page_my)
        self.label_3.setGeometry(QtCore.QRect(50, 100, 101, 131))
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.page_my)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.label_7.setStyleSheet("\n"
"font: 15pt \"Algerian\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page_my)
        self.page_salary = QtWidgets.QWidget()
        self.page_salary.setObjectName("page_salary")
        self.label_4 = QtWidgets.QLabel(self.page_salary)
        self.label_4.setGeometry(QtCore.QRect(200, 170, 81, 101))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.page_salary)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 161, 41))
        self.label_6.setStyleSheet("\n"
"font: 15pt \"Algerian\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.page_salary)
        self.page_edit = QtWidgets.QWidget()
        self.page_edit.setObjectName("page_edit")
        self.label_5 = QtWidgets.QLabel(self.page_edit)
        self.label_5.setGeometry(QtCore.QRect(200, 140, 101, 121))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.page_edit)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 111, 41))
        self.label_8.setStyleSheet("\n"
"font: 15pt \"Algerian\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.label_8.setObjectName("label_8")
        self.frame_9 = QtWidgets.QFrame(self.page_edit)
        self.frame_9.setGeometry(QtCore.QRect(0, 479, 641, 40))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_9)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(240, 10, 121, 21))
        self.label_2.setStyleSheet("font: 12pt \"Algerian\";\n"
"color: rgb(255, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.stackedWidget_2.addWidget(self.page_2)
        self.horizontalLayout_6.addWidget(self.stackedWidget_2)
        self.stackedWidget.addWidget(self.page_edit)
        self.horizontalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton.clicked.connect(MainWindow.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "用户界面"))
        self.pushButton_Seach.setText(_translate("MainWindow", "薪水查询"))
        self.pushButton_Edit.setText(_translate("MainWindow", "查询/编辑\n"
"他人工资"))
        self.pushButton_My.setText(_translate("MainWindow", "我的"))
        self.label_3.setText(_translate("MainWindow", "当前等级\n"
"当月薪水\n"
"工号\n"
"身份\n"
"(传值进来)"))
        self.label_7.setText(_translate("MainWindow", "个人信息"))
        self.label_4.setText(_translate("MainWindow", "当月工资\n"
"工资合计"))
        self.label_6.setText(_translate("MainWindow", "个人薪资情况"))
        self.label_5.setText(_translate("MainWindow", "他人工资\n"
"修改他人工资"))
        self.label_8.setText(_translate("MainWindow", "修改薪水"))
        self.label_2.setText(_translate("MainWindow", "您没有权限"))
import res_rc
